### PR TITLE
updates on the lit review

### PR DESCRIPTION
**Pull request by JorgeValdebenito**
Please let me know if I am correctly sending the pdf and the .tex files in this pull request

### CODE REVIEW

**Comment by kbuzard** [comment]
Yes, I see both files.

But somehow the relationship between the .tex file in the previous commit and this one was lost. Did you change the name? When looking under the "Files Changed" tab in split view, I should be able to see that most of the file was there before, and on the right it should just highlight the parts that have changed. But Github thinks this is an entirely new file. This needs to be resolved before I can understand what's going on.

**Comment by JorgeValdebenito** [comment]
OK, I think I know what is going on. 
I didn't change the name of the files, but
When I send you the first file, I didn't fork it to my account, instead I created it directly in your repository and send the pull request from there. 
Then, when I send you (today) the updated pdf and the .tex file, I fork them to my account and then I send the pull request from my repository. This is the correct way to do it and I think that is why github thinks is a new file. I can send you another pull request with a small variation in the title of the pdf to prove this if you like, but it will only replace this latest file, not the one I send you yesterday. 
I apologize for the problems.

**Comment by kbuzard** [comment]
I'll send you an email in a few minutes about how we're going to resolve this. For now, I'm closing this pull request because we need to do some other things to clean this up.

**Comment by kbuzard** [comment]
I changed the file name so that it matches (Github is case sensitive, and
the file extension--in this case the .tex--matters). I thought this would
resolve the problem--i.e. that I don't want two versions of this file in
the repository.

BUT now Github sees them as the same file, but somehow Github while now
sees the two as the same file, it can't merge them. So we need to take the
original file (attached) out of the main repository and have you make a
pull request for it from your fork, and THEN go ahead and make these
changes--that is, keep the current version of you file in another location
when you make the first pull request, then replace the earlier version in
your fork with the updated one.

I have now deleted all the changes that have been made in the last couple
of days, so you can start fresh. To be clear, I want you to start with the
earliest version of Literature review.tex (and please add an underscore
between the words--otherwise, I have to constantly put the name in
quotation marks when I'm working at the command line) so that we have the
history of the changes that were made.

**Comment by JorgeValdebenito** [comment]
Professor, 
I sent you the files again. 
Please, let me know if I did this right. 
I feel like I should have sent you 2 pull request, one for each file, but its only showing me one pull request. 
I tried to send you the original file, from my fork, and then update the files and send them to you again, but I'm worried that I just may have overwritten the first pull request. Maybe I need to wait until you have accepted the original files and then I can send you the updated version. 
I am very sorry about the confusion and all the issues.

**Pull request closed without merging**
